# Generated by Django 4.2 on 2024-10-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessAI', '0002_appointment_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
