# Generated by Django 4.2 on 2024-10-29 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessAI', '0006_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='clinic_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='contact',
            new_name='phone',
        ),
    ]
