# Generated by Django 4.2 on 2024-11-07 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WellnessAI', '0011_remove_symptomdetail_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_frequency', models.PositiveIntegerField()),
                ('diet_quality', models.PositiveIntegerField()),
                ('sleep_hours', models.PositiveIntegerField()),
                ('appointment_feedback', models.CharField(choices=[('helpful', 'Helpful'), ('somewhat helpful', 'Somewhat Helpful'), ('not helpful', 'Not Helpful')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='chatbotInteraction',
        ),
        migrations.DeleteModel(
            name='diseasePrediction',
        ),
        migrations.DeleteModel(
            name='notificationsAlerts',
        ),
        migrations.DeleteModel(
            name='recommendation',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
        migrations.DeleteModel(
            name='Usersymptoms',
        ),
        migrations.AlterField(
            model_name='symptomdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
