# Generated by Django 4.2 on 2024-11-07 19:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WellnessAI', '0013_updateddata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='updatedData',
            new_name='updateData',
        ),
    ]
