# Generated by Django 4.2 on 2024-11-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessAI', '0014_rename_updateddata_updatedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatedata',
            name='address',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='updatedata',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='updatedata',
            name='gender',
            field=models.CharField(default='Not specified', max_length=10),
        ),
        migrations.AddField(
            model_name='updatedata',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='updatedata',
            name='phone',
            field=models.CharField(default='Unknown', max_length=15),
        ),
        migrations.AddField(
            model_name='updatedata',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
