# Generated by Django 4.2 on 2024-11-08 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessAI', '0015_updatedata_address_updatedata_age_updatedata_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
    ]
